spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    application:
        name: mkhFramework
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        properties:
#              hibernate.cache.use_second_level_cache: true
#              hibernate.cache.use_query_cache: false
#              hibernate.cache.region.factory_class: org.roshan.frm.config.NoDefaultJCacheRegionFactory
              #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
              #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
              hibernate.generate_statistics: false
              hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
              hibernate.show_sql : true
              hibernate.current_session_context_class:  org.springframework.orm.hibernate5.SpringSessionContext
    messages:
        basename: i18n/messages
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sepehrnet?useUnicode=yes&characterEncoding=utf8&useSSL=false
        username: root
        password: 891369
        hikari:
          #jdbc-url: jdbc:mysql://localhost:3306/ihs?useUnicode=yes&characterEncoding=utf8&useSSL=false
          maximum-pool-size: 50
          data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

    security:
        basic:
            enabled: false

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
    port: 8082
    servlet:
#        servlet-path: /api
        context-path: /app


frm:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers: "X-Total-Count,link"
        allow-credentials: true
        max-age: 1800
#    security:
#        rememberMe:
#            key: 5c37379956bd1242f5636c8cb322c2966ad81277
#        authentication:
#            jwt:
#                secret: 3a3f158dfe9fd36d08e26d5fcd55b36442b8ada9
#                tokenValidityInSeconds: 86400

